
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 17;
  public static final int especial = 21;
  public static final int coma = 10;
  public static final int llave_abre = 3;
  public static final int numero = 19;
  public static final int flecha = 11;
  public static final int llave_cierra = 4;
  public static final int concat = 8;
  public static final int porcentaje = 7;
  public static final int punto_y_coma = 6;
  public static final int or = 13;
  public static final int dos_puntos = 5;
  public static final int EOF = 0;
  public static final int letra = 18;
  public static final int id = 16;
  public static final int virgulilla = 9;
  public static final int symbol = 20;
  public static final int error = 1;
  public static final int plus = 14;
  public static final int interrogacion = 15;
  public static final int klenee = 12;
  public static final int reservada_conjunto = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "reservada_conjunto",
  "llave_abre",
  "llave_cierra",
  "dos_puntos",
  "punto_y_coma",
  "porcentaje",
  "concat",
  "virgulilla",
  "coma",
  "flecha",
  "klenee",
  "or",
  "plus",
  "interrogacion",
  "id",
  "cadena",
  "letra",
  "numero",
  "symbol",
  "especial"
  };
}

